name: Run Click CLI

on:
  workflow_dispatch:

jobs:
  cli-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run CLI extract command
      run: |
        python cli_sql_etl.py extract --table [dbo].[Accounts]

    - name: Upload output CSV
      uses: actions/upload-artifact@v3
      with:
        name: extracted-data
        path: extracted_sql.csv