name: Run Click CLI

on:
  workflow_dispatch:

jobs:
  cli-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install ODBC Driver for SQL Server
      run: |
        sudo apt-get update
        sudo apt-get install -y curl gnupg
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev

    - name: Inject SQL environment variables
      run: |
        echo "SQL_SERVER=${{ secrets.SQL_SERVER }}" >> $GITHUB_ENV
        echo "SQL_DATABASE=${{ secrets.SQL_DATABASE }}" >> $GITHUB_ENV
        echo "SQL_USER=${{ secrets.SQL_USER }}" >> $GITHUB_ENV
        echo "SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}" >> $GITHUB_ENV

    - name: Run CLI extract command
      run: |
        python cli_sql_etl.py extract --table [dbo].[Accounts]
        python cli_sql_etl.py transform --drop-null
        python cli_sql_etl.py load --target final_output.csv
        python cli_sql_etl.py report
        python cli_sql_etl.py validate



    - name: Upload output CSV
      uses: actions/upload-artifact@v4
      with:
        name: extracted-data
        path: extracted_sql.csv